image: node:22

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm run test
          - npm run build
          - npx eslint