services:
  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob Storage
    volumes:
      - azurite-data:/data
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000  --location /data --debug /data/debug.log"

volumes:
  pgdata:
  azurite-data: